"""empty message

Revision ID: b1be97a14950
Revises: 50d6aaac25a6
Create Date: 2021-10-16 14:07:34.880730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1be97a14950'
down_revision = '50d6aaac25a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('name', sa.String(length=200), nullable=True))
    op.add_column('cart', sa.Column('price', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'price')
    op.drop_column('cart', 'name')
    # ### end Alembic commands ###
